version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - 'typescript'
          - 'vitest'
          - 'turbo'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
      expo:
        patterns:
          - 'expo*'
          - 'react-native*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5

  - package-ecosystem: 'docker'
    directory: '/apps/simulate'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5

  - package-ecosystem: 'docker'
    directory: '/apps/client'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
